services:
    mongodb:
        image: 'mongo:8.3.7'
        container_name: filmkritiken-mongodb
        environment:
            - MONGO_INITDB_DATABASE=mongodb
        command: ["--replSet", "rs0", "--bind_ip_all"]
        healthcheck:
            test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'filmkritiken-mongodb:27017'}]}) }" | mongosh --quiet
            interval: 5s
            timeout: 30s
            start_period: 0s
            start_interval: 1s
            retries: 30
        volumes:
            - mongo_data:/data/db
        ports:
            - '27017-27019:27017-27019'
    mongo-express:
        image: 'mongo-express'
        container_name: filmkritiken-mongo-express
        restart: unless-stopped
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://filmkritiken-mongodb:27017
            - ME_CONFIG_BASICAUTH_ENABLED=false
        ports:
            - '8082:8081'

volumes:
    mongo_data:

networks:
    default:
        name: filmkritiken
        external: true
