name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

#    - name: Set up Go
#      uses: actions/setup-go@v2
#      with:
#        go-version: 1.16

#    - name: Build
#      run: make build

#    - name: Test
#      run: make test

    - name: Build an image from Dockerfile
      run: |
        docker build -t derblum/filmkritiken-backend:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'derblum/filmkritiken-backend:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
