name: Deploy

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: [Build]
    types: [completed]


env:
  FULL_IMAGE_NAME: ghcr.io/derblum/filmkritiken-backend:release

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@master

      - name: CapRover deploy with Token
        uses: MrFreasy/action-caprover@v2
        with:
          host: 'https://captain.marsrover.418-teapot.de'
          app: 'filmkritiken-backend'
          token: '${{ secrets.CAPROVER_APP_TOKEN }}'
          image: '${{ env.FULL_IMAGE_NAME }}'

  noop:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "No deployment after failed build"
