name: Deploy

on:
  workflow_run:
    workflows: [Build_Push]
    types: [completed]


env:
  FULL_IMAGE_NAME: ghcr.io/derblum/filmkritiken-backend:release

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'master' && github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@master

      - name: CapRover deploy with Token
        uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
        with:          
          server: 'https://captain.marsrover.418-teapot.de'
          app: 'filmkritiken-backend'
          token: '${{ secrets.CAPROVER_APP_TOKEN }}'
          image: '${{ env.FULL_IMAGE_NAME }}'

  noop:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name != 'master' || github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          echo "No deployment because of wrong branch ($GITHUB_REF_NAME) or failure of build step"
        
